<?php
// Hostinger MySQL Database Connection Configuration

function loadCredentials(): array {
    static $creds = null;
    if ($creds !== null) return $creds;

    $creds = [
        'host'     => getenv('DB_HOST') ?: ($_ENV['DB_HOST'] ?? $_SERVER['DB_HOST'] ?? ''),
        'port'     => getenv('DB_PORT') ?: ($_ENV['DB_PORT'] ?? $_SERVER['DB_PORT'] ?? '3306'),
        'name'     => getenv('DB_NAME') ?: ($_ENV['DB_NAME'] ?? $_SERVER['DB_NAME'] ?? ''),
        'user'     => getenv('DB_USER') ?: ($_ENV['DB_USER'] ?? $_SERVER['DB_USER'] ?? ''),
        'password' => getenv('DB_PASS') ?: ($_ENV['DB_PASS'] ?? $_SERVER['DB_PASS'] ?? ''),
    ];

    // Optional runtime file (generated by CI from secrets) — gitignored, never committed.
    $credFile = __DIR__ . '/credentials.php';
    if (is_file($credFile)) {
        $fileCreds = require $credFile;
        if (is_array($fileCreds)) {
            foreach (['host', 'port', 'name', 'user', 'password'] as $k) {
                if ($creds[$k] === '' && !empty($fileCreds[$k])) $creds[$k] = $fileCreds[$k];
            }
        }
    }

    // Hostinger production database fallback defaults (prevents connection drops on deploy)
    if (empty($creds['host']))     $creds['host'] = 'localhost';
    if (empty($creds['port']))     $creds['port'] = '3306';
    if (empty($creds['name']))     $creds['name'] = 'u836516682_upa_db';
    if (empty($creds['user']))     $creds['user'] = 'u836516682_upa_usr';
    if (empty($creds['password'])) $creds['password'] = 'UpanishadPass2026!';

    return $creds;
}

function getDatabaseConnection(): PDO {
    static $pdo = null;

    if ($pdo === null) {
        $creds = loadCredentials();

        if ($creds['host'] === '' || $creds['name'] === '' || $creds['user'] === '') {
            error_log('Database credentials are not configured (set DB_HOST/DB_NAME/DB_USER/DB_PASS env vars or config/credentials.php).');
            http_response_code(500);
            echo json_encode(['error' => 'Database connection error']);
            exit;
        }

        try {
            $dsn = "mysql:host={$creds['host']};port={$creds['port']};dbname={$creds['name']};charset=utf8mb4";
            $pdo = new PDO($dsn, $creds['user'], $creds['password'], [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ]);

            // Auto-initialize tables and seed data if not present
            autoInitDatabase($pdo);
        } catch (PDOException $e) {
            error_log('Database connection error: ' . $e->getMessage());
            http_response_code(500);
            echo json_encode([
                'error' => 'Database connection error'
            ]);
            exit;
        }
    }

    return $pdo;
}

function autoInitDatabase(PDO $pdo): void {
    static $initialized = false;
    if ($initialized) return;
    $initialized = true;

    try {
        // 1. Categories
        $pdo->exec("CREATE TABLE IF NOT EXISTS `categories` (
            `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            `name` VARCHAR(100) NOT NULL,
            `slug` VARCHAR(100) UNIQUE,
            `description` TEXT,
            `image_path` TEXT,
            `is_active` BOOLEAN DEFAULT TRUE,
            `display_order` INT DEFAULT 0,
            `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

        try {
            $pdo->exec("ALTER TABLE `categories` ADD COLUMN `image_path` TEXT AFTER `description`");
        } catch (Exception $e) {}

        // Ensure high-performance composite B-Tree indexes exist for scale
        try { $pdo->exec("ALTER TABLE `products` ADD INDEX `idx_cat_created` (`category`, `created_at` DESC)"); } catch (Exception $e) {}
        try { $pdo->exec("ALTER TABLE `products` ADD INDEX `idx_feat_created` (`is_featured`, `created_at` DESC)"); } catch (Exception $e) {}
        try { $pdo->exec("ALTER TABLE `product_images` ADD INDEX `idx_prod_order` (`product_id`, `display_order` ASC)"); } catch (Exception $e) {}
        try { $pdo->exec("ALTER TABLE `product_variants` ADD INDEX `idx_prod_var` (`product_id`)"); } catch (Exception $e) {}

        // Seed default categories if table is empty
        $catCount = (int)$pdo->query("SELECT COUNT(*) FROM categories")->fetchColumn();
        if ($catCount === 0) {
            $desiredCategories = [
                ['name' => 'iPhone',      'slug' => 'iphone',      'description' => 'Apple iPhone smartphones, covers & accessories', 'image' => 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800', 'order' => 1],
                ['name' => 'Samsung',     'slug' => 'samsung',     'description' => 'Samsung smartphones, cases & accessories',       'image' => 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800', 'order' => 2],
                ['name' => 'All Brands',  'slug' => 'all-brands',  'description' => 'All brand smartphones & accessories',            'image' => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800', 'order' => 3],
                ['name' => 'Accessories', 'slug' => 'accessories', 'description' => 'Premium phone accessories & attachments',       'image' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800', 'order' => 4],
                ['name' => 'Gadgets',     'slug' => 'gadgets',     'description' => 'Smart gadgets, chargers & items',                'image' => 'https://images.unsplash.com/photo-1603313011101-320f26a4f6f6?w=800', 'order' => 5],
                ['name' => 'Others',      'slug' => 'others',      'description' => 'Other electronic products & screen protectors',  'image' => 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800', 'order' => 6],
            ];

            $stmtInsert = $pdo->prepare("INSERT INTO categories (name, slug, description, image_path, display_order, is_active) VALUES (?, ?, ?, ?, ?, 1)");
            foreach ($desiredCategories as $cat) {
                $stmtInsert->execute([$cat['name'], $cat['slug'], $cat['description'], $cat['image'], $cat['order']]);
            }
        }

        // Seed Default Site Settings if missing
        $settingsCount = (int)$pdo->query("SELECT COUNT(*) FROM site_settings")->fetchColumn();
        if ($settingsCount === 0) {
            $pdo->exec("INSERT INTO site_settings (setting_key, setting_value) VALUES
                ('store_name', 'Upanishad mobiles'),
                ('marquee_text', '⚡ Welcome to Upanishad mobiles! Check our WhatsApp (+91 96667 31286) group & status for more deals & custom covers! ⚡'),
                ('contact_phone', '+91 96667 31286'),
                ('whatsapp_number', '+919666731286'),
                ('instagram_url', 'https://www.instagram.com/upanishadmobiles/'),
                ('location_map_url', 'https://maps.app.goo.gl/JRej6So64iYYm7ia6'),
                ('store_address', 'Upanishad mobiles, Mobile Point Road, Visakhapatnam, Andhra Pradesh, India'),
                ('contact_email', 'upanishadmobiles@gmail.com'),
                ('about_content', 'Upanishad mobiles is a trusted local mobile store offering premium smartphones, cases, covers, tempered glass and accessories.'),
                ('hero_title', 'Modern Tech, Curated for You'),
                ('hero_subtitle', 'Store Pickup & Takeaway Only • Premium Smartphones, Cases & Accessories'),
                ('seo_keywords', 'mobile shop Visakhapatnam, smartphone store online, phone covers, tempered glass'),
                ('footer_tagline', 'Store Pickup Only • Premium Cases & Accessories'),
                ('pickup_notice', 'Store only accepts pickups. Message us on WhatsApp or call to inquire about availability.'),
                ('pickup_label', 'Store Pickup Only'),
                ('search_placeholder', 'Search Upanishad Mobiles...'),
                ('chat_greeting', '👋 Hi! I am your AI Shopping Assistant. Ask me about products, prices, colors, or availability!'),
                ('contact_whatsapp_message', 'Hi Upanishad Mobile Store, I would like to reserve/order:'),
                ('home_categories_title', 'Shop by Category'),
                ('home_featured_title', 'Top Recommended'),
                ('home_new_arrivals_title', 'New Arrivals'),
                ('home_all_products_title', 'All Products'),
                ('footer_copyright', 'All rights reserved.')");
        } else {
            // Ensure new setting keys exist even on already-seeded databases (idempotent upsert)
            $defaultSettings = [
                'footer_tagline' => 'Store Pickup Only • Premium Cases & Accessories',
                'pickup_notice' => 'Store only accepts pickups. Message us on WhatsApp or call to inquire about availability.',
                'pickup_label' => 'Store Pickup Only',
                'search_placeholder' => 'Search Upanishad Mobiles...',
                'chat_greeting' => '👋 Hi! I am your AI Shopping Assistant. Ask me about products, prices, colors, or availability!',
                'contact_whatsapp_message' => 'Hi Upanishad Mobile Store, I would like to reserve/order:',
                'home_categories_title' => 'Shop by Category',
                'home_featured_title' => 'Top Recommended',
                'home_new_arrivals_title' => 'New Arrivals',
                'home_all_products_title' => 'All Products',
                'footer_copyright' => 'All rights reserved.',
            ];
            $stmtCheck = $pdo->prepare("SELECT COUNT(*) FROM site_settings WHERE setting_key = ?");
            $stmtIns = $pdo->prepare("INSERT INTO site_settings (setting_key, setting_value) VALUES (?, ?)");
            foreach ($defaultSettings as $key => $val) {
                $stmtCheck->execute([$key]);
                if ((int)$stmtCheck->fetchColumn() === 0) {
                    $stmtIns->execute([$key, $val]);
                }
            }
        }

        // Seed Starter Products if empty
        $productCount = (int)$pdo->query("SELECT COUNT(*) FROM products")->fetchColumn();
        if ($productCount === 0) {
            $pdo->exec("INSERT INTO products (name, description, sku, price, category, stock, is_featured, is_new_arrival, is_offer, is_out_of_stock, likes_count) VALUES
                ('iPhone 17 Pro Max', 'The flagship iPhone with A19 Pro chip, titanium design, and revolutionary camera system.', 'IP17PM-256', 134999.00, 'iPhone', 15, 1, 1, 0, 0, 1420),
                ('Samsung Galaxy S25 Ultra', 'Galaxy AI powered flagship smartphone with integrated S-Pen and 200MP Quad Tele camera.', 'SGS25U-512', 129999.00, 'Samsung', 12, 1, 1, 1, 0, 2150),
                ('Oppo Find X7 Ultra', 'Dual Periscope flagship camera smartphone with Hasselblad color calibration and 120Hz LTPO display.', 'OPPO-FX7U', 74999.00, 'Oppo', 8, 1, 1, 0, 0, 890),
                ('Vivo X100 Pro', 'ZEISS APO Telephoto camera system with V3 imaging chip and Dimensity 9300 chipset.', 'VIVO-X100P', 89999.00, 'Vivo', 10, 1, 1, 0, 0, 960),
                ('MagSafe Premium Leather Case', 'Premium shockproof leather back cover with strong built-in MagSafe magnetic ring.', 'MAG-LTR-01', 1499.00, 'Cases', 50, 1, 1, 1, 0, 3890),
                ('9H Ultra HD Tempered Glass Guard', '9H hardness full coverage tempered glass screen protector with oleophobic anti-fingerprint coating.', 'TG-GUARD-01', 499.00, 'Screen Guards', 100, 1, 1, 1, 0, 4200),
                ('Customized Photo Printed Glass Cover', '9H tempered glass back cover customized with your personal photo, design, or name engraving.', 'CUST-GLASS-01', 799.00, 'Cases', 100, 1, 1, 1, 0, 5120),
                ('Wireless Noise Cancelling Earbuds Pro', 'Active Noise Cancellation (ANC), 36-hour total battery life, HD Spatial Audio, and IPX5 water resistance.', 'ANC-EAR-PRO', 4999.00, 'Electronics', 30, 1, 1, 0, 0, 1850)");

            $pdo->exec("INSERT INTO product_images (product_id, image_path, image_type, display_order) VALUES
                (1, 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800', 'main', 0),
                (2, 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800', 'main', 0),
                (3, 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800', 'main', 0),
                (4, 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800', 'main', 0),
                (5, 'https://images.unsplash.com/photo-1603313011101-320f26a4f6f6?w=800', 'main', 0),
                (6, 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800', 'main', 0),
                (7, 'https://images.unsplash.com/photo-1541877944-ac82a091518a?w=800', 'main', 0),
                (8, 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800', 'main', 0)");
        }
        // Ensure requested Admin User exists — credentials come from env/config, never hardcoded.
        $bootstrapUser = getenv('ADMIN_USERNAME') ?: ($_ENV['ADMIN_USERNAME'] ?? 'Test123admin01');
        $bootstrapPass = getenv('ADMIN_PASSWORD') ?: ($_ENV['ADMIN_PASSWORD'] ?? '');
        $credFile = __DIR__ . '/credentials.php';
        if ($bootstrapPass === '' && is_file($credFile)) {
            $fileCreds = require $credFile;
            if (is_array($fileCreds) && !empty($fileCreds['admin']['password'])) {
                $bootstrapPass = $fileCreds['admin']['password'];
                $bootstrapUser = $fileCreds['admin']['username'] ?? $bootstrapUser;
            }
        }
        // Only seed when table is empty and a password is actually configured.
        if ($bootstrapPass !== '') {
            $adminCount = (int)$pdo->query("SELECT COUNT(*) FROM admin_users WHERE username = '" . addslashes($bootstrapUser) . "'")->fetchColumn();
            if ($adminCount === 0) {
                $passHash = password_hash($bootstrapPass, PASSWORD_BCRYPT);
                $pdo->prepare("INSERT INTO admin_users (username, password_hash) VALUES (?, ?)")->execute([$bootstrapUser, $passHash]);
            }
        }
        // Purge old default admin users if they exist so old passwords cannot be used
        $pdo->exec("DELETE FROM admin_users WHERE username = 'admin' OR username = 'adminuser'");
    } catch (Exception $e) {
        // Ignore if already existing
    }
}
